"""
main.py – Script principal : lance la recherche sur toutes les conjectures du benchmark.
Usage:
    python src/main.py [--mode simple|funsearch] [--time 60] [--benchmark benchmark/benchmark.xlsx]
"""
import sys
import os
import time
import json
import argparse
import random

_script_dir = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.dirname(_script_dir)
sys.path.insert(0, _script_dir)
os.chdir(_project_root)

from conjecture import load_benchmark
from heuristic import search_counterexample
from funsearch import build_funsearch, search_counterexample_funsearch


def run_benchmark(benchmark_path: str, mode: str = "simple",
                  time_limit: float = 60.0, verbose: bool = True):
    """
    Lance la recherche sur toutes les conjectures du benchmark.
    """
    print(f"\n{'='*60}")
    print(f"GraphBench Challenge – Mode: {mode.upper()}")
    print(f"Limite de temps: {time_limit}s par conjecture")
    print(f"{'='*60}\n")

    conjectures = load_benchmark(benchmark_path)
    print(f"[INFO] {len(conjectures)} conjectures chargees.\n")

    results = []
    total_score = 0
    n_found = 0

    # FunSearch: evolution + selection de la meilleure fonction de score
    best_score_fn = None
    if mode == "funsearch":
        print("[FunSearch] Demarrage de l'evolution (Groq LLM + offline)...\n")
        fs = build_funsearch(conjectures, n_sample=8, n_iterations=6, groq_budget=6)
        best_score_fn = fs.get_best_function()

        os.makedirs("results", exist_ok=True)
        with open("results/best_score_function.py", "w") as f:
            f.write(fs.get_best_code())
        generated = fs.get_all_generated_codes()
        if generated:
            with open("results/groq_generated_functions.py", "w") as f:
                f.write(f"# {len(generated)} functions generated by Groq\n\n")
                for i, code in enumerate(generated, 1):
                    f.write(f"# ── Generated #{i} ──\n{code}\n\n")
        print(f"\n[FunSearch] Pret. Meilleure fonction sauvegardee dans results/best_score_function.py\n")

    # Lancer la recherche
    for i, conj in enumerate(conjectures):
        print(f"[{i+1:3d}/{len(conjectures)}] Conjecture {conj.id}: "
              f"{conj.y_name} {conj.sign} f({conj.x_name}) | Classes: {conj.graph_classes}")

        t_start = time.time()

        if mode == "funsearch" and best_score_fn is not None:
            result = search_counterexample_funsearch(
                conj, time_limit=time_limit,
                score_fn=best_score_fn, verbose=verbose
            )
        else:
            result = search_counterexample(conj, time_limit=time_limit, verbose=verbose)

        elapsed = time.time() - t_start

        if result is not None:
            cost = elapsed
            n_found += 1
            print(f"        [OK] TROUVE en {elapsed:.2f}s | "
                  f"violation={result.violation:.4f} | "
                  f"n={result.G.number_of_nodes()} m={result.G.number_of_edges()} | "
                  f"g6={result.graph6[:40]}...")
            results.append({
                "conjecture_id": conj.id,
                "found": True,
                "time": round(elapsed, 3),
                "cost": round(cost, 3),
                "violation": round(result.violation, 6),
                "graph6": result.graph6,
                "n": result.G.number_of_nodes(),
                "m": result.G.number_of_edges(),
                "invariants": {k: round(v, 6) if isinstance(v, float) else v
                               for k, v in result.invariants.items()},
            })
        else:
            cost = 120.0
            print(f"        [--] Non trouve (cout = 120)")
            results.append({
                "conjecture_id": conj.id,
                "found": False,
                "time": round(elapsed, 3),
                "cost": 120.0,
                "violation": None,
                "graph6": None,
            })

        total_score += cost
        print(f"        Score cumulé: {total_score:.1f}\n")

    # Résumé
    print("\n" + "=" * 60)
    print("RÉSULTATS FINAUX")
    print("=" * 60)
    print(f"Conjectures réfutées : {n_found}/{len(conjectures)}")
    print(f"Score total          : {total_score:.1f}")
    if n_found > 0:
        avg_time = sum(r['time'] for r in results if r['found']) / n_found
        print(f"Temps moyen (trouvés): {avg_time:.2f}s")
    print("=" * 60)

    return results, total_score, n_found


def main():
    parser = argparse.ArgumentParser(description="GraphBench – Réfutation automatique de conjectures")
    parser.add_argument("--mode", choices=["simple", "funsearch"], default="simple",
                        help="Mode: 'simple' (Partie 1) ou 'funsearch' (Partie 2)")
    parser.add_argument("--time", type=float, default=60.0,
                        help="Limite de temps par conjecture (secondes)")

    _script_dir = os.path.dirname(os.path.abspath(__file__))
    _candidates = [
        os.path.join(_project_root, "benchmark", "benchmark.xlsx"),
        os.path.join(_project_root, "benchmark.xlsx"),
        os.path.join(_script_dir, "benchmark.xlsx"),
        "benchmark/benchmark.xlsx",
        "benchmark.xlsx",
    ]
    _default_benchmark = next((p for p in _candidates if os.path.exists(p)), _candidates[0])

    parser.add_argument("--benchmark", type=str, default=_default_benchmark,
                        help="Chemin vers le fichier benchmark xlsx")
    parser.add_argument("--output", type=str, default=None,
                        help="Fichier de sortie JSON")
    parser.add_argument("--verbose", action="store_true", default=False)
    args = parser.parse_args()

    os.makedirs("results", exist_ok=True)

    results, total_score, n_found = run_benchmark(
        benchmark_path=args.benchmark,
        mode=args.mode,
        time_limit=args.time,
        verbose=args.verbose,
    )

    output_path = args.output or f"results/results_{args.mode}.json"
    with open(output_path, "w") as f:
        json.dump({
            "mode": args.mode,
            "total_score": round(total_score, 3),
            "n_found": n_found,
            "n_total": len(results),
            "results": results,
        }, f, indent=2)

    print(f"\n[INFO] Résultats sauvegardés dans {output_path}")
    return total_score


if __name__ == "__main__":
    main()
